### PR TITLE
feat: store contact thumbnail in local database

### PR DESCRIPTION
**Pull request by SERDUN**

### CODE REVIEW

**Comment by ycherniavskyi** [comment]
Task linked: [CU-86954ckyj Phone contact images](https://app.clickup.com/t/86954ckyj)

**Comment by SERDUN** [comment]
I won’t close the task in ClickUp as I plan to create a subtask in it for the correct functioning of Gravatar, but I propose to merge this pull request if everything is fine.

**Review by ycherniavskyi — CHANGES_REQUESTED** [review]
It seems that this PR is incomplete. Currently, it causes a compile error when attempting to run the tests.
```
flutter test
00:00 +0: loading /.../webtrit_phone/packages/data/app_database/test/migrations_test.dart                                                                                      lib/src/app_database.g.dart:1920:48: Error: Expected 8 type arguments.
class $$ContactsTableTableTableManager extends RootTableManager<
                                               ^^^^^^^^^^^^^^^^
...
```

**Comment by ycherniavskyi** [comment]
The issue was on my side. After deleting `pubspec.lock` and executing `dart pub get` within `/packages/data/app_database`, the test executed without errors.

**Review by ycherniavskyi — APPROVED** [review]

**Pull request merged**
